### ISSUE TITLE
Wont Load

### ISSUE THREAD

**Issue by BajanVlogs** [kenygamer/KillMoney#1]
26.06 16:15:57 [Server] Server thread/INFO [KillMoney] Disabling KillMoney v1.1.0... 26.06 16:15:57 [Server] Server thread/INFO Disabling KillMoney v1.1.0 26.06 16:15:57 [Server] Server thread/INFO [KillMoney] Disabling plugin, enable.plugin is set to false. 26.06 16:15:57 [Server] Server thread/INFO Enabling KillMoney v1.1.0

how do i enable it please tell me

**Comment by BajanVlogs** [comment]
@kenygamer when i kill someone it doesnt give me money i dont want it to steal money from others

**Comment by kenygamer** [comment]
@BajanVlogs Open another issue for that suggestion.

**Comment by BajanVlogs** [comment]
well i have seen a server that u get money when killing someone

**Comment by kenygamer** [comment]
@BajanVlogs Please review the updated comment, and open another issue with your other question.

**Comment by kenygamer** [comment]
@BajanVlogs If the *config.yml* does not exist, the plugin will not work either. That is why it is essential to check the console *log*.

**Comment by kenygamer** [comment]
Closing.- Issue solved.
Only open if there are still problems.
#
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ
