### ISSUE TITLE
Killmoney idea

### ISSUE THREAD

**Issue by BajanVlogs** [kenygamer/KillMoney#2]
can you make it where people earn money when they kill someone instead of stealing someones money

**Comment by kenygamer** [comment]
@BajanVlogs This feature already comes: use a permission manager such as **PurePerms** and set the permissions you need:
- `killmoney.killer.receive.money` => Will give money to the killer.
- Killmoney.victim.lose.money` => The victim will lose money.

**Comment by kenygamer** [comment]
#3

**Comment by kenygamer** [comment]
Closing.- Issue solved.
Only open if there are still problems.
#
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ
