### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by SuperAlecs** [kenygamer/KillMoney#2]
#### Description

When you kill a player it didn't give you money.

#### Versions

* PocketMine Version:  PocketMine-MP 1.7dev-866
* KillMoney Version: 1.0.0-beta 
* Game Version: PE / Windows 10

#### Crashdump or console errors

```
```

**Comment by kenygamer** [comment]
Please post your `config.yml` contents

**Comment by SuperAlecs** [comment]
It's the original one

**Comment by kenygamer** [comment]
@SuperAlecs Can you check if EconomyAPI is installed?

**Comment by SuperAlecs** [comment]
Yes and it is also detected by killmoney

**Comment by kenygamer** [comment]
Please download the release from the downloads page again.
