### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by SuperAlecs** [kenygamer/KillMoney#3]
Could you add a feature to give the kill with the last cause of damage?

**Comment by SuperAlecs** [comment]
When the damager dead and it was by fire or other cause, it gave the kill to the killer if the damager got hit by the killer

**Comment by kenygamer** [comment]
I'm going to release a major KillMoney update on August, the date is inaccurate. I will consider your feature request & add support to the latest API.

Thanks for the patience.

**Comment by kenygamer** [comment]
> When the damager dead and it was by fire or other cause, it gave the kill to the killer if the damager got hit by the killer

The plugin already functions like that.
