### ISSUE TITLE
Please Update To API 3.1.0

### ISSUE THREAD

**Issue by joshuasing** [kenygamer/KillMoney#4]
#### Description

Hi! i run a kitpvp server and really need this plugin.
but it's outdated. Please Update to API 3.1.0 & 4.0.0 Thank You.
#### Versions

* PocketMine Version: PocketMine-MP 3.2.0 For Minecraft Bedrock Edition.
* KillMoney Version: N/A (I Can't Get It Because It's Outdated.)
* Game Version: PE / Windows 10

#### Crashdump or console errors

None (I Can't Get It Because It's Outdated.)

**Comment by LoloD22NR** [comment]
Plzzz update plzz

**Comment by kenygamer** [comment]
I'm going to release a major KillMoney update on August, the date is inaccurate. I will add support to the latest API.

Thanks for the patience.

**Comment by joshuasing** [comment]
Thank you.

**Comment by kenygamer** [comment]
KillMoney may be only of the few plugins I will keep support for. Please pop me a message on Discord to stay connected: kenygamer#0783
