### ISSUE TITLE
Hey bro ! I love you plz update

### ISSUE THREAD

**Issue by LoloD22NR** [kenygamer/KillMoney#5]
#### Versions

* PocketMine Version:
* KillMoney Version:
* Game Version: PE / Windows 10

#### Crashdump or console errors

```
```

**Comment by kenygamer** [comment]
I'm going to release a major KillMoney update on August, the date is inaccurate. I will add support to the latest API.

Thanks for the patience.

**Comment by kenygamer** [comment]
Updated. Check [releases](https://github.com/kenygamer/KillMoney/releases/tag/v1.0.0-stable)
